### ISSUE TITLE
Fluentd stops processing the logs if a pod is restarted

### ISSUE THREAD

**Issue by dhineshbabuelango** [vmware/kube-fluentd-operator#296] opened 2021-12-08 05:01 UTC
Hi Team, 
We are using fluentd in EKS cluster, we are injesting logs from a file in the container to fluentd through a configmap, using grok parser, while the initial setup working fine everytime when a deployment or pod is restarted, we had to recreate the config map(without any change) as well only then fluentd processing the logs

**Comment by Cryptophobia** [comment] 2021-12-08 17:42
This is a known issue with file-mount logs.

See https://github.com/vmware/kube-fluentd-operator/issues/289

Duplicate of https://github.com/vmware/kube-fluentd-operator/issues/289

**Comment by Cryptophobia** [comment] 2021-12-08 17:43
Duplicate of #289

**Closed** 2021-12-08 17:43 UTC

**Comment by Cryptophobia** [comment] 2021-12-08 17:44
`docker.io/vmware/kube-fluentd-operator:v1.16.2` may fix your problems if you don't run very large clusters with lots of configs.

**Comment by dhineshbabuelango** [comment] 2021-12-09 01:10
Is this issue only with type mounted-file?, if so can I use any other type.
Note: the logs of my container are piped to a different folder like /app/jboss/logs and not the stdout and stderr. So in this case my only option is mounted-file?

**Comment by Cryptophobia** [comment] 2021-12-10 21:02
> Is this issue only with type mounted-file?, if so can I use any other type.

Yes, it only affects mounted-file types.

We are working on a resolution that may work. Are you able to switch to logging to stdout for the jboss server in the container/pod? If you do that then you will not face this problem when pods restart.

**Comment by dhineshbabuelango** [comment] 2021-12-23 07:18
@Cryptophobia Thanks for the update, we are in process of moving the logs to stdout but since we have some applications already running in prod we are finding for a fix. The mounted-file plugin only supports emptydir volume or we can use a persistant storage as well for this.

**Comment by dhineshbabuelango** [comment] 2022-01-03 06:04
@Cryptophobia If I restart teh configmap in few seconds to minutes, will fluentd be able to capture all the logs without any miss?

**Comment by Cryptophobia** [comment] 2022-01-03 17:31
> @Cryptophobia Thanks for the update, we are in process of moving the logs to stdout but since we have some applications already running in prod we are finding for a fix. The mounted-file plugin only supports emptydir volume or we can use a persistant storage.

@dhineshbabuelango , KFO only supports mounted-files logs as `emptyDir` types so persistent storage would not work at this time. When KFO makes representation in its memory for each of the pods, it only takes into account volumetypes that are `emptyDir` types.

> @Cryptophobia If I restart teh configmap in few seconds to minutes, will fluentd be able to capture all the logs without any miss?

If you write a hook to reload the configmap to delete and recreate the configmap right away after restarting the pods, it should work. It needs to happen right after the restart of the pods though.

**Comment by dhineshbabuelango** [comment] 2022-01-04 02:20
@Cryptophobia thanks for your response. Will refreshing(delete & recreate) the configmap will lead to fluentd missing any of the logs that was currently reading during the restart ?
